name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up environment variable
        run: |
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env

      - name: Deploy
        run: python deploy.py
